


create sequence branch_seq as integer;
create table branch (
    branch_id integer GENERATED BY DEFAULT AS SEQUENCE branch_seq PRIMARY KEY,
    name  varchar(128)
);


insert into branch (branch_id, name) values (NULL, 'ROOT');

