

--create sequence framez_seq as integer;
--
--create table FrameZ (
--    id integer GENERATED BY DEFAULT AS SEQUENCE framez_seq,
--    branch integer default 0 not null,
--    s0 varchar(255),
--    s1 varchar(255),
--    s2 varchar(255),
--    primary key (id, branch)
--);


create table FrameZ (
id integer generated by default as identity (start with 1),
branch integer,
s0 varchar(255),
s1 varchar(255),
s2 varchar(255),
primary key (id, branch)
);

