
create sequence foo_seq as integer;

create table foo (
    id integer  GENERATED BY DEFAULT AS SEQUENCE foo_seq,
    branch integer,
    vstart integer default 1,
    vend   integer default 2147483647 not null,
    s0 varchar(255),
    s1 varchar(255),
    s2 varchar(255),
    primary key(id, branch, vstart)
);

insert into foo values (1, 1, 1, default, 's0', 's1', 's2');

